name: Build or Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      action_type:
        description: "Type of action you want to execute ('build' or 'destroy')"
        required: true

env:
  AWS_REGION: ap-southeast-2
  IAM_ROLE: "arn:aws:iam::350357692482:role/GH-A"
permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    if: inputs.action_type == 'build'

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate
      
      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: false

      - name: Terraform Apply
        id: apply
        run: terraform apply-all
        continue-on-error: false